### ISSUE TITLE
URI for organizations

### ISSUE THREAD

**Issue by barthanssens** [belgif/inspire-dcat#14]
FYI, we now have official URIs for legal entities registered by the CrossroadBank Enterprises, so I'd suggest to use them for e.g. publishers (if possible, since obviously only legal entities / establishment units are registered, not e.g parts of organizations / brand names)

Example: F¨S BOSA is https://org.belgif.be/id/CbeRegisteredEntity/0671516647

**Comment by bfrichet3** [comment]
that's very good we should write something here about that as we should use them in INSPIRE metadata too (as the regions)

**Comment by celinevil** [comment]
A new section will be added to specify the use of URI.
