### ISSUE TITLE
DCATFederalProfile vs DCATAPprofil

### ISSUE THREAD

**Issue by barthanssens** [belgif/inspire-dcat#20]
Looks like the [DCATFederalProfile.md](https://github.com/belgif/inspire-dcat/blob/main/DCATFederalProfile.md) is an older copy of [DCATAPprofil.fr.md](https://github.com/belgif/inspire-dcat/blob/main/DCATAPprofil.fr.md).
So the DCATFederalProfile should probably be deleted, and/or a language selection page should be created instead (similar to README.md and README.fr.md / README.nl.md)

**Comment by celinevil** [comment]
DCATFederalProfile is indeed an older copy of DCATAPprofil.fr.md. The file is now deleted.
