### ISSUE TITLE
dct:language dans Distribution

### ISSUE THREAD

**Issue by marielleadam** [belgif/inspire-dcat#22]
Nous avons travaillé à la préparation de notre catalogue DCAT pour l’open-data et également d’un catalogue pour nos brochures.
Une question s’est posée par rapport à l’utilisation de dct:language. Je m’explique…
Si nous prenons l’exemple des brochures, nous les avons en français et en néerlandais, l’une étant la traduction de l’autre.
Suivant le profil DCAT, nous avons donc créé un dataset, pour lequel nous avons dct:language = FR et = NL. Ensuite, nous avons 2 distributions qui correspondent au fichier PDF des brochures en NL et en FR. Mais dct:language n’est pas repris dans les propriétés de la distribution. Et nous n’avons dès lors pas la possibilité de préciser la langue de la distribution. Cela peut aussi se poser par exemple pour des datasets dont les distributions sont des fichiers excel, un pour le FR et un pour le NL.

Comment pouvons-nous procéder ? Ne pouvons-nous pas ajouter dct:language comme propriété optionnelle (cardinalité = 0-1) d’une distribution, comme cela est évoqué ici :  [https://joinup.ec.europa.eu/collection/semantic-interoperability-community-semic/solution/dcat-application-profile-data-portals-europe/discussion/dctlanguage-distribution](https://eur06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fjoinup.ec.europa.eu%2Fcollection%2Fsemantic-interoperability-community-semic%2Fsolution%2Fdcat-application-profile-data-portals-europe%2Fdiscussion%2Fdctlanguage-distribution&data=05%7C01%7Cceline.vilain%40ngi.be%7C3b815889839c4fec8fa408da84ed6c1f%7Ca7070084ac554dc988342009ecd7519a%7C0%7C0%7C637968452506888542%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=NRlB47ZCiSoOt%2BN5GEyslc0J0J05LoV1Bj9GGiaZvpM%3D&reserved=0) 
“If representations of a dataset are available for each language separately, define an instance of dcat:Distribution for each language and describe the specific language of each distribution using dct:language (i.e. the dataset will have multiple dct:language values and each distribution will have just one as the value of its dct:language property).”

**Comment by marielleadam** [comment]
Réponse de Céline:
Cela semble la bonne solution au problème (qui est d’ailleurs évoqué par Bart dans ton lien..). 
On ajoute donc l’attribut dct:language à la classe dct:Distribution en Recommended et cardinalité 0-1.

**Comment by barthanssens** [comment]
I'd suggest a cardinality 0 - 4, since some distributions might be in multiple languages (e.g. an Excel file with the list of municipalities in nl/fr/de/en in the same file)

**Comment by celinevil** [comment]
The attribute dct:language is added to the the class distribution as recommended and cardinality 0-4.
