### ISSUE TITLE
SHACL: split or use sh:Info/warning

### ISSUE THREAD

**Issue by barthanssens** [belgif/inspire-dcat#38]
How should the recommended (= not mandatory) rules/shapes be checked:

- either use the recommended cardinality etc, but with sh:Warning / sh:Info (benefit: everything in 1 file, drawback: the reporting tool has to do more processing / distinguish between warning and violation)

- create a separate shacl for testing these recommended properties (benefit: cleaner separation, drawback: multiple files)

**Comment by barthanssens** [comment]
After some internal discussion: use sh:Info for recommended (but not mandatory) + everything in 1 file

**Comment by celinevil** [comment]
SHACL adapted
