### ISSUE TITLE
dcat:DataService/dct:conformsTo XPATH

### ISSUE THREAD

**Issue by CMath04** [belgif/inspire-dcat#9]
In the definition of the dcat:DataService, two dct:conformsTo are defined.  
Both of them have the same mapped XPATH: `//*/gmd:dataQualityInfo/gmd:DQ_DataQuality/gmd:report/gmd:DQ_DomainConsistency/gmd:result/gmd:DQ_ConformanceResult/gmd:specification/gmd:CI_Citation`.  

However, one is described as the mapping for the Information relative to the quality of the dataset and has the domain "dct:Standard" linked to http://www.opengis.net/def/crs/EPSG/0/.  
And the other is described as the mapping for the CRS but has its domain is linking to https://inspire.ec.europa.eu/metadata-codelist/ProtocolValue.

Shouldn't the first one be the mapping for the CRS with XPATH `//*gmd:referenceSystemInfo/gmd:MD_ReferenceSystem/gmd:referenceSystemIdentifier/gmd:RS_Identifier/gmd:code` and adapted description.
And the second one be to mapping for the protocol of the service with XPATH `//*/gmd:distributionInfo/gmd:MD_Distribution/gmd:transferOptions/*/gmd:onLine/*/gmd:protocol/*` and adapted description ?

**Comment by celinevil** [comment]
OK. We will change it.
